### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'foobar-test' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by dimino** [dimino/foobar-test#1]
Needs docker and docker-compose installed first.

After running these commands:
```bash
docker-compose build
docker-compose up foobar-worker
```

Traceback: 

```Python Traceback
Traceback (most recent call last):
  File "/usr/local/bin/the-foobar-worker", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3195, in <module>
     @_call_aside
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3179, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3208, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 681, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 999, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 885, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'foobar-test' distribution was not found and is required by the application
```

**Comment by dimino** [comment]
The generated script file looks like this:

```Python
#!/usr/local/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'foobar-test','console_scripts','the-foobar-worker'
__requires__ = 'foobar-test'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('foobar-test', 'console_scripts', 'the-foobar-worker')()
    )
```
